# Generated by Django 2.0.7 on 2018-07-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('servicio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('total_factura', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
